language: cpp

before_install:
 # - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 # - sudo apt-get install libfftw3-dev libopenmpi-dev libx11-dev zlib1g-dev libgsl0-dev libxml2-dev libblas-dev liblapack-dev libboost-dev cmake
 # - sudo apt-get update -y
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:opm/ppa
 - sudo apt-get update -y
 - sudo apt-get install -y build-essential gfortran pkg-config cmake
 - sudo apt-get install -y doxygen ghostscript texlive-latex-recommended pgf gnuplot
 - sudo apt-get install -y git-core
 - sudo apt-get install -y mpi-default-dev
 - sudo apt-get install -y libblas-dev libboost-all-dev libsuitesparse-dev libtrilinos-zoltan-dev
 - sudo apt-get install -y libdune-common-dev libdune-geometry-dev libdune-istl-dev libdune-grid-dev
 - sudo apt-get install -y unzip


 - git clone https://github.com/MatheusFerraroni/opm-common.git && mkdir opm-common/build && cd opm-common/build &&  cmake .. -DUSE_MPI=1 && make -j4
 - git clone https://github.com/MatheusFerraroni/opm-material.git && mkdir opm-material/build && cd opm-material/build &&  cmake .. -DUSE_MPI=1 && make -j4
 - git clone https://github.com/MatheusFerraroni/opm-grid.git && mkdir opm-grid/build && cd opm-grid/build &&  cmake .. -DUSE_MPI=1 && make -j4
 - git clone https://github.com/MatheusFerraroni/opm-models.git && mkdir opm-models/build && cd opm-models/build &&  cmake .. -DUSE_MPI=1 && make -j4


script: 
  - mkdir build && pushd build && cmake .. -DUSE_MPI=1 && make -j4

compiler:
  - clang
  - gcc
  - cmake