language: cpp

dist: bionic

before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:opm/ppa
 - sudo apt-get update -y
 - sudo apt-get install -y build-essential
 - sudo apt-get install -y gfortran
 - sudo apt-get install -y pkg-config
 - sudo apt-get install -y cmake
 - sudo apt-get install -y doxygen
 - sudo apt-get install -y ghostscript
 - sudo apt-get install -y texlive-latex-recommended
 - sudo apt-get install -y gnuplot
 - sudo apt-get install -y git-core
 - sudo apt-get install -y mpi-default-dev
 - sudo apt-get install -y libblas-dev
 - sudo apt-get install -y libboost-all-dev
 - sudo apt-get install -y libsuitesparse-dev
 - sudo apt-get install -y libtrilinos-zoltan-dev
 - sudo apt-get install -y libdune-common-dev
 - sudo apt-get install -y libdune-geometry-dev
 - sudo apt-get install -y libdune-istl-dev
 - sudo apt-get install -y libdune-grid-dev
 - sudo apt-get install -y unzip


script: 
  - lsb_release -a
  - cmake --version
  - make --version
  - cd ../
  - git clone https://github.com/MatheusFerraroni/opm-common.git
  - mkdir ./opm-common/build
  - git clone https://github.com/MatheusFerraroni/opm-material.git
  - mkdir ./opm-material/build
  - git clone https://github.com/MatheusFerraroni/opm-grid.git
  - mkdir ./opm-grid/build
  - git clone https://github.com/MatheusFerraroni/opm-models.git
  - mkdir ./opm-models/build
  - mkdir ./opm-simulators/build
  - git clone https://github.com/MatheusFerraroni/opm-data.git
  - cmake --version
  - make --version
  - cd ./opm-common/build
  - cmake ..
  - make -j4
  - cd ../../
  - cd opm-material/build
  - cmake ..
  - make -j4
  - cd ../../
  - cd opm-grid/build
  - cmake ..
  - make -j4
  - cd ../../
  - cd opm-models/build
  - cmake ..
  - make -j4
  - cd ../../
  - cd opm-simulators/build
  - cmake ..
  - travis_wait make -j2
  - cd ../../opm-data/norne
  - ../../opm-simulators/build/bin/flow --max-pi=10 NORNE_ATW2013.DATA


compiler:
  - cmake