language: cpp

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:opm/ppa
  - sudo apt-get update -y
  - sudo apt-get install -y build-essential gfortran pkg-config cmake git
  - sudo apt-get install -y doxygen ghostscript texlive-latex-recommended pgf gnuplot
  - sudo apt-get install -y git-core
  - sudo apt-get install -y mpi-default-dev
  - sudo apt-get install -y libblas-dev libboost-all-dev libsuitesparse-dev libtrilinos-zoltan-dev
  - sudo apt-get install -y libdune-common-dev libdune-geometry-dev libdune-istl-dev libdune-grid-dev
  - sudo apt-get install -y unzip
  - sudo apt-get install -y binutils make

script: 
  - cd ../
  - git clone https://github.com/MatheusFerraroni/opm-common.git
  - mkdir ./opm-common/build
  - git clone https://github.com/MatheusFerraroni/opm-material.git
  - mkdir ./opm-material/build
  - git clone https://github.com/MatheusFerraroni/opm-grid.git
  - mkdir ./opm-grid/build
  - git clone https://github.com/MatheusFerraroni/opm-models.git
  - mkdir ./opm-models/build
  - mkdir ./opm-simulators/build
  - cd ./opm-common/build
  - cmake .. -DUSE_MPI=1
  - make -j


  # - cd /home/travis/MatheusFerraroni/
  # - git clone https://github.com/MatheusFerraroni/opm-common.git
  # - mkdir /home/travis/MatheusFerraroni/opm-common/build
  # - cd /home/travis/MatheusFerraroni/opm-common/build 
  # - cmake .. -DUSE_MPI=1 && make -j
  # - cd ../ && git clone https://github.com/MatheusFerraroni/opm-material.git && mkdir opm-material/build && cd opm-material/build &&  cmake .. -DUSE_MPI=1 && make -j4
  # - cd ../ && git clone https://github.com/MatheusFerraroni/opm-grid.git && mkdir opm-grid/build && cd opm-grid/build &&  cmake .. -DUSE_MPI=1 && make -j4
  # - cd ../ && git clone https://github.com/MatheusFerraroni/opm-models.git && mkdir opm-models/build && cd opm-models/build &&  cmake .. -DUSE_MPI=1 && make -j4
  # - cd mkdir build && pushd build && cmake .. -DUSE_MPI=1 && make -j4

compiler:
  - clang
  - gcc
  - cmake