language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - software-properties-common
      - build-essential
      - gfortran
      - pkg-config
      - cmake
      - doxygen
      - ghostscript
      - texlive-latex-recommended
      - gnuplot
      - git-core
      - mpi-default-dev
      - libblas-dev
      - libboost-all-dev
      - libsuitesparse-dev
      - libtrilinos-zoltan-dev
      - libdune-common-dev
      - libdune-geometry-dev
      - libdune-istl-dev
      - libdune-grid-dev
      - unzip

env:
  global:
  - TRAVIS_CI=1


before_script:
    - export CXX="g++-4.8" CC="gcc-4.8" FC="gfortran-4.8"
    - cd ..
    - git clone https://github.com/MatheusFerraroni/opm-common.git
    # - opm-common/travis/build-prereqs.sh
    # - opm-common/travis/clone-opm.sh opm-common
    

script: cd opm-common/ && mkdir build && cd build && cmake .. && make
# script: opm-common/travis/build-and-test.sh opm-common



# language: cpp

# before_install:
#  - sudo apt-get update -y
#  - sudo apt-get install -y software-properties-common
#  - sudo add-apt-repository -y ppa:opm/ppa
#  - sudo apt-get update -y
#  - sudo apt-get install -y build-essential
#  - sudo apt-get install -y gfortran
#  - sudo apt-get install -y pkg-config
#  - sudo apt-get install -y cmake
#  - sudo apt-get install -y doxygen
#  - sudo apt-get install -y ghostscript
#  - sudo apt-get install -y texlive-latex-recommended
#  - sudo apt-get install -y gnuplot
#  - sudo apt-get install -y git-core
#  - sudo apt-get install -y mpi-default-dev
#  - sudo apt-get install -y libblas-dev
#  - sudo apt-get install -y libboost-all-dev
#  - sudo apt-get install -y libsuitesparse-dev
#  - sudo apt-get install -y libtrilinos-zoltan-dev
#  - sudo apt-get install -y libdune-common-dev
#  - sudo apt-get install -y libdune-geometry-dev
#  - sudo apt-get install -y libdune-istl-dev
#  - sudo apt-get install -y libdune-grid-dev
#  - sudo apt-get install -y unzip

# script: 
#   - cmake --version
#   - make --version
#   - cd ../
#   - git clone https://github.com/MatheusFerraroni/opm-common.git
#   - mkdir ./opm-common/build
#   - git clone https://github.com/MatheusFerraroni/opm-material.git
#   - mkdir ./opm-material/build
#   - git clone https://github.com/MatheusFerraroni/opm-grid.git
#   - mkdir ./opm-grid/build
#   - git clone https://github.com/MatheusFerraroni/opm-models.git
#   - mkdir ./opm-models/build
#   - mkdir ./opm-simulators/build
#   - cd ./opm-common/build
#   - cmake ..
#   - make


#   # - cd /home/travis/MatheusFerraroni/
#   # - git clone https://github.com/MatheusFerraroni/opm-common.git
#   # - mkdir /home/travis/MatheusFerraroni/opm-common/build
#   # - cd /home/travis/MatheusFerraroni/opm-common/build 
#   # - cmake .. -DUSE_MPI=1 && make -j
#   # - cd ../ && git clone https://github.com/MatheusFerraroni/opm-material.git && mkdir opm-material/build && cd opm-material/build &&  cmake .. -DUSE_MPI=1 && make -j4
#   # - cd ../ && git clone https://github.com/MatheusFerraroni/opm-grid.git && mkdir opm-grid/build && cd opm-grid/build &&  cmake .. -DUSE_MPI=1 && make -j4
#   # - cd ../ && git clone https://github.com/MatheusFerraroni/opm-models.git && mkdir opm-models/build && cd opm-models/build &&  cmake .. -DUSE_MPI=1 && make -j4
#   # - cd mkdir build && pushd build && cmake .. -DUSE_MPI=1 && make -j4

# compiler:
#   - clang
#   - gcc
#   - cmake